on:
  push:
    branches:
    - master

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Check Commit Message [skip CI]
      env:
        COMMIT_FILTER: "[skip ci]"
      if: contains(github.event.head_commit.message, '[skip ci]')
      run: |
        echo "no 'skip ci' in commit message"
        exit 2

    - uses: googleapis/release-please-action@v4
      id: release
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        release-type: simple
